import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './computents/Navbar'
import Footer from './computents/Footer'
import Providers from '@/providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

 const RootLayout= ({ children })=> {
  return (
    <html lang="en">
  
      <body className={inter.className}>


  <Providers>
  <div>  {children}</div>
  </Providers>

 
        

        </body>
    </html>
  )
}
export default RootLayout